# **FIFA 21 Players Dataset - Data Cleaning & Transform**

 Welcome to the FIFA 21 Players Dataset - Data Cleaning & Transformation project! In this Python project, we aim to explore and prepare a dataset containing information about football players from the popular video game FIFA 21.
 
 The dataset provides a comprehensive collection of attributes for each player, including their skills, positions, clubs, and more. However, like any real-world dataset, it may contain imperfections that could hinder analysis and modeling.

### **Our Quest**:

1. **Tackling Heights and Weights:** Are the height and weight columns in the right format?
2. **Untangling Join Dates:** Can we split the 'Joined' column into year, month, and day?
3. **Monetary Makeover:** Let's turn 'value', 'wage', and 'release clause' into tidy columns of integers.
4. **Scrubbing Special Characters:** Banish those pesky unnecessary characters from all columns.
5. **A Decade on the Field:** Using the 'Joined' column, identify players who've been loyal to a club for over a decade.

### **Setting Up Shop**:
First things first, let's import our trusty libraries and configure our workspace settings. Let the games begin!

In [1]:
import pandas as pd
from datetime import datetime, timedelta

pd.set_option('display.max_columns', None)

In [ ]:
df_ = pd.read_csv('fifa21 raw data v2.csv')

In [3]:
df = df_.copy()

In [4]:
df.head(5)

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,Preferred Foot,BOV,Best Position,Joined,Loan Date End,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,72kg,Left,93,RW,"Jul 1, 2004",NaN,€103.5M,€560K,€138.4M,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4 ★,4★,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,2018 ~ 2022,"ST, LW",187cm,83kg,Right,92,ST,"Jul 10, 2018",NaN,€63M,€220K,€75.9M,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4 ★,5★,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,2014 ~ 2023,GK,188cm,87kg,Right,91,GK,"Jul 16, 2014",NaN,€120M,€125K,€159.4M,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3 ★,1★,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,2015 ~ 2023,"CAM, CM",181cm,70kg,Right,91,CAM,"Aug 30, 2015",NaN,€129M,€370K,€161M,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5 ★,4★,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,68kg,Right,91,LW,"Aug 3, 2017",NaN,€132M,€270K,€166.5M,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5 ★,5★,High,Medium,5 ★,91,85,86,94,36,59,595

In [5]:
df.tail(5)

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,Preferred Foot,BOV,Best Position,Joined,Loan Date End,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
18974,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,55,\n\n\n\nWuhan Zall,2018 ~ 2022,CB,178cm,66kg,Right,49,CB,"Jul 13, 2018",NaN,€100K,€1K,€70K,145,23,26,43,26,27,142,27,23,21,29,42,294,68,60,69,46,51,221,36,57,54,50,24,192,48,50,28,28,38,44,147,45,52,50,45,7,8,5,14,11,1186,255,2 ★,2★,Medium,Medium,1 ★,64,28,26,38,48,51,NaN
18975,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,67,\n\n\n\nOldham Athletic,2020 ~ 2021,CM,175cm,65kg,Right,51,CAM,"Aug 1, 2020",NaN,€130K,€500,€165K,211,38,42,40,56,35,219,46,40,35,50,48,305,63,64,61,51,66,226,48,58,43,47,30,193,40,23,47,47,36,38,116,32,44,40,45,12,10,9,6,8,1315,281,2 ★,2★,Medium,Medium,1 ★,64,40,48,49,35,45,NaN
18976,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47,65,\n\n\n\nDerry City,2019 ~ 2020,CM,179cm,74kg,Right,49,CAM,"Mar 8, 2019",NaN,€120K,€500,€131K,200,30,34,43,54,39,207,43,39,31,47,47,290,59,66,51,47,67,242,45,52,50,54,41,230,56,42,47,43,42,43,121,33,43,45,48,13,12,6,6,11,1338,285,2 ★,2★,Medium,Medium,1 ★,63,39,44,46,40,53,NaN
18977,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47,57,\n\n\n\nDalian YiFang FC,2020 ~ 2022,RW,175cm,69kg,Right,48,ST,"Sep 22, 2020",NaN,€100K,€2K,€88K,215,45,52,34,42,42,194,51,35,31,31,46,254,62,55,50,33,54,235,56,45,46,48,40,190,31,25,42,46,46,45,100,26,32,42,55,14,12,9,8,12,1243,271,3 ★,2★,Medium,Medium,1 ★,58,49,41,49,30,44,NaN
18978,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,57,\n\n\n\nDalian YiFang FC,2019 ~ 2023,"CB, LB",188cm,75kg,Left,50,LB,"Jul 29, 2019",NaN,€100K,€1K,€79K,163,40,18,40,45,20,171,40,33,20,40,38,279,60,63,57,47,52,231,37,66,60,55,13,185,45,47,33,33,27,33,136,45,46,45,50,10,11,7,10,12,1215,265,3 ★,2★,Medium,Medium,1 ★,62,22,39,42,45,55,NaN

### **1 - Tackling Heights and Weights:** 

Are the height and weight columns in the right format?

In [6]:
print('Data Type of Column Height is:',df['Height'].dtype)
print('Data Type of Column Weight is:',df['Weight'].dtype)

Data Type of Column Height is: object
Data Type of Column Weight is: object

The 'Height' and 'Weight' variables are object and need to be converted to integer data types for proper data analysis. <br>To achieve this, we need to remove text such as 'cm' or 'kg' from these variables first.

In [7]:
df['Height'] = df['Height'].str.extract('(\d+)').astype(int)
df['Weight'] = df['Weight'].str.extract('(\d+)').astype(int)

In [8]:
print('Data Type of Column Height is:',df['Height'].dtype)
print('Data Type of Column Weight is:',df['Weight'].dtype)

Data Type of Column Height is: int32
Data Type of Column Weight is: int32

As seen, the 'Height' and 'Weight' columns have been converted to the integer data type. They are now suitable for analysis.

### **2 - Untangling Join Dates:** 

Can we split the 'Joined' column into year, month, and day?

In [10]:
print('Data Type of Column Joined is:',df['Joined'].dtype)

df[['Joined']]

Data Type of Column Joined is: object

             Joined
0       Jul 1, 2004
1      Jul 10, 2018
2      Jul 16, 2014
3      Aug 30, 2015
4       Aug 3, 2017
...             ...
18974  Jul 13, 2018
18975   Aug 1, 2020
18976   Mar 8, 2019
18977  Sep 22, 2020
18978  Jul 29, 2019

[18979 rows x 1 columns]

We can use **datetime** library to split the "Joined" column. This library can convert between different date formats, eliminating the need for us to use regex.

In [11]:
df['Joined'] = pd.to_datetime(df['Joined'])

df['Joined_Year'] = df['Joined'].dt.year
df['Joined_Month'] = df['Joined'].dt.month
df['Joined_Day'] = df['Joined'].dt.day

df[['Joined','Joined_Year','Joined_Month','Joined_Day']]

          Joined  Joined_Year  Joined_Month  Joined_Day
0     2004-07-01         2004             7           1
1     2018-07-10         2018             7          10
2     2014-07-16         2014             7          16
3     2015-08-30         2015             8          30
4     2017-08-03         2017             8           3
...          ...          ...           ...         ...
18974 2018-07-13         2018             7          13
18975 2020-08-01         2020             8           1
18976 2019-03-08         2019             3           8
18977 2020-09-22         2020             9          22
18978 2019-07-29         2019             7          29

[18979 rows x 4 columns]

As we've seen, the 'Joined' column has now been separated into year, month, and day.

### **3 - Monetary Makeover:** 

Let's turn 'value', 'wage', and 'release clause' into tidy columns of integers.

In [133]:
df[['Wage', 'Value', 'Release Clause']]

        Wage    Value Release Clause
0      €560K  €103.5M        €138.4M
1      €220K     €63M         €75.9M
2      €125K    €120M        €159.4M
3      €370K    €129M          €161M
4      €270K    €132M        €166.5M
...      ...      ...            ...
18974    €1K    €100K           €70K
18975   €500    €130K          €165K
18976   €500    €120K          €131K
18977    €2K    €100K           €88K
18978    €1K    €100K           €79K

[18979 rows x 3 columns]

As we've seen, the **Wage**, **Value**, and **Release Claus** columns contain characters such as **€**, **K**, and **M** that would hinder us from converting the variable type to integer. <br> Let's now write a function that removes these characters from the given column and converts it to integer format.

In [134]:
def clean_financial_data(data):
    if data.endswith('K'):
        return int(float(data[1:-1]) * 1000)
    elif data.endswith('M'):
        return int(float(data[1:-1]) * 1000000)
    else:
        return int(data[1:])

df['Wage'] = df['Wage'].apply(clean_financial_data)
df['Value'] = df['Value'].apply(clean_financial_data)
df['Release Clause'] = df['Release Clause'].apply(clean_financial_data)

df[['Wage', 'Value', 'Release Clause']]

         Wage      Value  Release Clause
0      560000  103500000       138400000
1      220000   63000000        75900000
2      125000  120000000       159400000
3      370000  129000000       161000000
4      270000  132000000       166500000
...       ...        ...             ...
18974    1000     100000           70000
18975     500     130000          165000
18976     500     120000          131000
18977    2000     100000           88000
18978    1000     100000           79000

[18979 rows x 3 columns]

As we can see, these variables are now in integer format.

### **4 - Scrubbing Special Characters:** 

Banish those pesky unnecessary characters from all columns.

In [12]:
df[['↓OVA','Club', 'W/F', 'SM', 'IR']]

       ↓OVA                         Club  W/F  SM   IR
0        93         \n\n\n\nFC Barcelona  4 ★  4★  5 ★
1        92             \n\n\n\nJuventus  4 ★  5★  5 ★
2        91      \n\n\n\nAtlético Madrid  3 ★  1★  3 ★
3        91      \n\n\n\nManchester City  5 ★  4★  4 ★
4        91  \n\n\n\nParis Saint-Germain  5 ★  5★  5 ★
...     ...                          ...  ...  ..  ...
18974    47           \n\n\n\nWuhan Zall  2 ★  2★  1 ★
18975    47      \n\n\n\nOldham Athletic  2 ★  2★  1 ★
18976    47           \n\n\n\nDerry City  2 ★  2★  1 ★
18977    47     \n\n\n\nDalian YiFang FC  3 ★  2★  1 ★
18978    47     \n\n\n\nDalian YiFang FC  3 ★  2★  1 ★

[18979 rows x 5 columns]

We've identified the columns that need to be changed. Now, let's fix them and convert the ones in numerical format to integers.

In [136]:
df = df.rename(columns = {'↓OVA':'OVA'})

df['Club'] = df['Club'].str.replace('\n', '')

df['W/F'] = df['W/F'].str.extract('(\d+)').astype(int)

df['SM'] = df['SM'].str.extract('(\d+)').astype(int)

df['IR'] = df['IR'].str.extract('(\d+)').astype(int)

df[['OVA','Club', 'W/F', 'SM', 'IR']]

       OVA                 Club  W/F  SM  IR
0       93         FC Barcelona    4   4   5
1       92             Juventus    4   5   5
2       91      Atlético Madrid    3   1   3
3       91      Manchester City    5   4   4
4       91  Paris Saint-Germain    5   5   5
...    ...                  ...  ...  ..  ..
18974   47           Wuhan Zall    2   2   1
18975   47      Oldham Athletic    2   2   1
18976   47           Derry City    2   2   1
18977   47     Dalian YiFang FC    3   2   1
18978   47     Dalian YiFang FC    3   2   1

[18979 rows x 5 columns]

### **5 - A Decade on the Field:**

Using the 'Joined' column, identify players who've been loyal to a club for over a decade.

In [137]:
release_date = datetime(2020,10,9)

diff = release_date - df['Joined']
filter = diff > timedelta(days=365*10)
dfm = df[filter]

dfm.head(10)

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,OVA,POT,Club,Contract,Positions,Height,Weight,Preferred Foot,BOV,Best Position,Joined,Loan Date End,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Joined_Year,Joined_Month,Joined_Day
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",170,72,Left,93,RW,2004-07-01,NaN,103500000,560000,138400000,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4,4,Medium,Low,5,85,92,91,95,38,65,771,2004,7,1
15,165153,K. Benzema,Karim Benzema,https://cdn.sofifa.com/players/165/153/21_60.png,http://sofifa.com/player/165153/karim-benzema/...,France,32,89,89,Real Madrid,2009 ~ 2022,"CF, ST",185,81,Right,89,CF,2009-07-09,NaN,83500000,350000,108700000,426,75,88,91,86,86,404,87,81,73,73,90,388,77,72,79,91,69,400,84,79,78,80,79,363,63,39,90,87,84,90,89,47,24,18,41,13,11,5,5,7,2111,442,4,4,Medium,Low,4,74,85,81,86,40,76,216,2009,7,9
16,155862,Sergio Ramos,Sergio Ramos García,https://cdn.sofifa.com/players/155/862/21_60.png,http://sofifa.com/player/155862/sergio-ramos-g...,Spain,34,89,89,Real Madrid,2005 ~ 2021,CB,184,82,Right,89,CB,2005-08-01,NaN,33500000,300000,50200000,374,66,65,92,82,69,381,65,74,76,83,83,378,72,70,78,92,66,402,79,93,81,85,64,414,90,88,73,71,92,88,263,85,88,90,46,11,8,9,7,11,2258,463,3,3,High,Medium,4,71,70,76,73,88,85,212,2005,8,1
23,202126,H. Kane,Harry Kane,https://cdn.sofifa.com/players/202/126/21_60.png,http://sofifa.com/player/202126/harry-kane/210...,England,26,88,89,Tottenham Hotspur,2010 ~ 2024,ST,188,89,Right,88,ST,2010-07-01,NaN,109000000,220000,140200000,420,75,94,85,81,85,395,80,80,68,83,84,367,66,69,69,90,73,424,91,79,84,84,86,382,81,35,93,83,90,91,130,56,36,38,54,8,10,11,14,11,2172,449,4,3,High,High,3,68,91,80,80,47,83,332,2010,7,1
39,138956,G. Chiellini,Giorgio Chiellini,https://cdn.sofifa.com/players/138/956/21_60.png,http://sofifa.com/player/138956/giorgio-chiell...,Italy,35,87,87,Juventus,2005 ~ 2021,CB,187,85,Left,87,CB,2005-07-01,NaN,21000000,95000,25600000,280,54,33,83,65,45,276,59,60,31,65,61,326,60,70,57,82,57,355,78,87,54,87,49,306,90,88,28,50,50,84,272,94,90,88,15,3,3,2,4,3,1830,399,3,2,Medium,High,4,66,46,58,60,90,79,130,2005,7,1
40,189511,Sergio Busquets,Sergio Busquets Burgos,https://cdn.sofifa.com/players/189/511/21_60.png,http://sofifa.com/player/189511/sergio-busquet...,Spain,31,87,87,FC Barcelona,2008 ~ 2023,"CDM, CM",189,76,Right,87,CDM,2008-09-01,NaN,56000000,240000,77900000,330,62,67,68,89,44,386,81,66,68,83,88,284,40,43,67,84,50,337,61,66,81,75,54,387,81,85,77,84,60,93,249,86,83,80,48,5,8,13,9,13,2021,424,3,3,Medium,Medium,4,42,62,80,80,83,77,119,2008,9,1
48,189596,T. Müller,Thomas Müller,https://cdn.sofifa.com/players/189/596/21_60.png,http://sofifa.com/player/189596/thomas-muller/...,Germany,30,86,86,FC Bayern München,2008 ~ 2023,"CAM, RM, RW",186,75,Right,86,CAM,2008-08-10,NaN,65500000,130000,69300000,419,85,85,81,84,84,375,75,81,59,78,82,374,68,68,73,94,71,388,78,77,86,66,81,359,62,58,94,85,60,84,150,47,57,46,52,6,7,11,14,14,2117,437,4,3,High,High,4,68,82,82,78,56,71,126,2008,8,10
55,152729,Piqué,Gerard Piqué Bernabeu,https://cdn.sofifa.com/players/152/729/21_60.png,http://sofifa.com/player/152729/gerard-pique-b...,Spain,33,86,86,FC Barcelona,2008 ~ 2022,CB,194,85,Right,86,CB,2008-07-01,NaN,32500000,220000,43100000,344,57,65,84,81,57,325,63,58,43,81,80,292,48,64,57,88,35,343,62,74,69,87,51,371,79,87,64,72,69,87,258,88,86,84,58,10,11,14,15,8,1991,422,3,2,High,Medium,4,57,61,71,67,86,80,175,2008,7,1
81,198219,L. Insigne,Lorenzo Insigne,https://cdn.sofifa.com/players/198/219/21_60.png,http://sofifa.com/player/198219/lorenzo-insign...,Italy,29,85,85,Napoli,2010 ~ 2022,"LW, CF",163,59,Right,85,LW,2010-07-01,NaN,53000000,120000,63800000,374,83,75,59,83,74,425,90,87,77,78,93,442,92,84,93,80,93,316,78,50,70,34,84,300,34,26,81,85,74,83,99,53,24,22,45,8,4,14,9,10,2001,420,4,4,High,Medium,3,88,78,83,91,36,44,116,2010,7,1
127,197445,D. Alaba,David Alaba,https://cdn.sofifa.com/players/197/445/21_60.png,http://sofifa.com/player/197445/david-alaba/21...,Austria,28,84,84,FC Bayern München,2010 ~ 2021,"CB, LB",180,78,Left,84,CB,2010-02-10,NaN,36500000,105000,45400000,368,80,60,76,85,67,401,77,77,85,79,83,396,78,77,76,88,77,394,82,83,75,76,78,388,74,84,73,78,79,84,250,85,83,82,50,5,7,14,15,9,2247,466,4,3,Medium,Medium,4,77,70,81,79,83,76,256,2010,2,10

For our final quest, we took the release date of the game as the upper limit for our time calculation, considering it as the most recent date the dataset is based on. <br> 
We created a filter for the desired condition of being loyal to a club over a decade, and applied it to the dataset to find what the final quest asked for.

### **Closing**
Let's finalize this project by saving our cleaned dataset as a CSV file.

In [13]:
df.to_csv('fifa21_cleaned_data.csv', index= False)